name: Industrialisation continue sur le serveur Alwaysdata
on: push
jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd $HOME/www/

      # - name: Run build
      #   run: |
      #     npm run build
  deploy:
    needs: Connexion
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: |
          npm install

      - name: run build
        run: |
          npm run build

           # Étape 5 : Archiver le contenu du répertoire `out`
      - name: Archiver le dossier `out`
        run: |
          tar -czf out.tar.gz out
        continue-on-error: false

  Copy:
    needs: Connexion
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            last_directory=$(basename ${{ runner.workspace }})
            cd $HOME/

            # Vérifier si le répertoire de destination existe
            if [ "$(ls -A ./www)" ]; then
              # rsync -r --delete ./$last_directory/ ./www
              # Transférer et extraire le contenu du fichier `out`
              tar -xzf ../out.tar.gz -C ./www
              rm -rf ./$last_directory
            else
              echo "Le répertoire flask de destination sur votre serveur n'existe pas"
              exit 1
            fi

  # # Update-htpasswd:
  # #   needs: Copy
  # #   runs-on: ubuntu-latest
  # #   steps:
  # #     - name: Connexion SSH et mise à jour htpasswd
  # #       uses: appleboy/ssh-action@master
  # #       with:
  # #         host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
  # #         username: ${{ secrets.USERNAME }}
  # #         password: ${{ secrets.PASSWORD }}
  # #         script: |
  # #           cd $HOME/www/atelier1
  # #           echo '${{ secrets.MY_SECRET_FILE_CONTENT }}' > .htpasswd
